### PR TITLE
fix:compilerFS.mkdirp is not a function (fix #414)

### LINKED ISSUE #414: [prerender-spa-plugin] Unable to prerender all routes! when upgrade webpack to v5+
ERROR in [prerender-spa-plugin] Unable to prerender all routes! 
this happened in webpack5, but work well in webpack4

node env: v12.18.2

error messages comes out with deeply debug;
image

image
image

webpack5 breaked here because of this:

[https://webpack.js.org/blog/2020-10-10-webpack-5-release/#filesystems](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#filesystems)

> Filesystems
> Next to compiler.inputFileSystem and compiler.outputFileSystem there is a new compiler.intermediateFileSystem for all fs actions that are not considered as input or output, like writing records, cache or profiling output.
> 
> The filesystems have now the fs interface and do no longer demand additional methods like join or mkdirp. But if they have methods like join or dirname they are used.
> 

code update here to be compatible with both webpack4/5

```
  // From https://github.com/ahmadnassri/mkdirp-promise/blob/master/lib/index.js
  const mkdirp = function (dir, opts) {
    return new Promise((resolve, reject) => {
      console.log('\ndir', dir, opts, '\n');
      try {
        compilerFS.mkdirp(dir, opts, (err, made) => err === null ? resolve(made) : reject(err))
      } catch(e) {
        compilerFS.mkdir(dir, opts, (err, made) => err === null ? resolve(made) : reject(err))
      }
    })
  }
```

### PR DESCRIPTION
**Pull request by lduoduo**
fixed issue [here](https://github.com/chrisvfritz/prerender-spa-plugin/issues/414)

### CODE REVIEW

**Comment by marcusds** [comment]
I really hope we can get this PR and some other open PRs merged in like #420.

Webpack 5 not working has broken our workflow completely.

**Comment by wojtekmaj** [comment]
I have tested this PR and I can confirm that this fix when applied fixes the plugin on Webpack 5.

**Comment by marcusds** [comment]
We've been using a fork with this fix applied in production with Webpack 5 without issue as well. It would be nice if it was merge into the main branch instead of having to maintain another fork.

**Comment by dmitryuk** [comment]
Any plans to accept the PR?

**Comment by Tofandel** [comment]
This project seems abandoned, I would direct you to [prerender-spa-plugin-next](https://www.npmjs.com/package/prerender-spa-plugin-next) (My fork for webpack 5 only, a few API changes but mostly backward compatible)
